### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by droccom** [alpha-unito/gam#22]

**Comment by droccom** [comment]
Fixed by #34.

**Comment by paoloviviani** [comment]
I would reopen the discussion to keep gam.hpp in the gam/include directory.
This is useful when using from external projects that only include gam.hpp as following
`#include "gam.hpp"`
As defining the following include path
`-I$(GAM_ROOT)/gam/include`
breaks the build as gam.hpp is not found.

While, including the lower level breaks the gam build itself.
`-I$(GAM_ROOT)/gam/include/gam`
breaks the includes in this way:
`../gam/include/gam/gam.hpp:40:10: fatal error: gam/Context.hpp: No such file or directory
 #include "gam/Context.hpp"  //ctx`

I'm in favor of the 
`#include "gam.hpp"`
as opposite to the approach
``#include "gam/gam.hpp"`
but the discussion is open.

**Comment by droccom** [comment]
I have no preference at all, let us switch to the compact way:
`#include "gam.hpp"`
I will change it both for gam and fastflow/d/gff tests

**Comment by droccom** [comment]
Should be fixed.

**Comment by droccom** [comment]
Fixed by #39.
